/***************************************************************************
 *   KEYDEFS.H      - defines for configurable keys                        *
 *                                                                         *
 *                  must match SETUP.C ordering                            *
 *                                                                         *
 *                                                          Les 07/22/95   *
 ***************************************************************************/

#define   KEYFWD         0
#define   KEYBACK        1
#define   KEYLEFT        2
#define   KEYRIGHT       3
#define   KEYRUN         4
#define   KEYSTRAFE      5
#define   KEYFIRE        6
#define   KEYUSE         7
#define   KEYJUMP        8
#define   KEYCROUCH      9
#define   KEYLKUP        10
#define   KEYLKDN        11
#define   KEYCNTR        12
#define   KEYSTFL        13
#define   KEYSTFR        14
#define   KEYMAP         15
#define   KEYZOOMI       16
#define   KEYZOOMO       17
#define   KEYUSEP        18
#define   KEYCAST        19
#define   KEYFLY         20
#define   KEYLOOKING     21
#define   KEYUNCAST      22
#define   KEYFLYUP       23
#define   KEYFLYDN       24
#define   KEYCYCSPELLUP  25
#define   KEYCYCSPELLDN  26
#define   KEYCYCPOTIONUP 27
#define   KEYCYCPOTIONDN 28
#define   KEYSHIELD      29
#define   NUMKEYS        30
