@echo off
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whaven.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whtag.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whplr.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whobj.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whinp.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whfx.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whmenu.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whani.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whnet.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h cdrom.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whctm.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whsmk.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h whsndmod.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h readcfg.c
wcc386 -d_PROTOTYPING_ -zs -zg -mf -or -zp4 -4r -Igcl520h profile.c
wtouch icorp.h
rem wh

